name: 'CI'
on:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: windows-latest
    steps:
     - uses: actions/checkout@v2
     - run: mvn test  
     - uses: actions/setup-java@v2
       with:
          java-version: '1.8'
          distribution: 'adopt'
