name: 'CI'
on:
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2         # checkout the repo
      - run: mvn test                      # install packages
      - uses: actions/upload-artifact@v2 # upload test results
        with:
          java-version: '15'
          distribution: 'adopt'